---

#
# Install Node build dependencies and other required software
#

- name: install NetWide Assembler
  win_chocolatey: name=nasm

- name: install CMake
  win_chocolatey:
    name: cmake
    install_args: 'ADD_CMAKE_TO_PATH=System'

- name: install Python 3
  win_chocolatey: name=python

- name: install Python 2
  win_chocolatey: name=python2

- block:
  - name: install Git
    win_chocolatey:
      name: git
      params: '/GitAndUnixToolsOnPath'
  - name: enable long paths in Git
    win_command: 'git config --global core.longpaths true'
  - name: set Git user name
    win_command: 'git config --global user.name "{{inventory_hostname}}"'
  - name: set Git user email
    win_command: 'git config --global user.email "ci@iojs.org"'

# Necessary for junit output in Jenkins jobs
- name: install tap2junit
  win_command: 'pip3 install --upgrade tap2junit'

# Necessary for the libuv test job
- block:
  - name: check if GYP is already cloned
    win_stat: path='C:\gyp'
    register: gyp_stat
  - name: clone GYP repository
    win_command: 'git clone https://chromium.googlesource.com/external/gyp C:\gyp'
    when: not gyp_stat.stat.exists
  - name: update GYP repository
    win_command: 'git pull'
    args: { chdir: 'C:\gyp' }
    when: gyp_stat.stat.exists

# Necessary for releases of older versions of Node
- block:
  - name: create node-icu directory
    win_file: path='C:\\node-icu' state=directory
  - name: download ICU2C 54 zip
    win_get_url:
      url: 'http://download.icu-project.org/files/icu4c/54.1/icu4c-54_1-src.zip'
      dest: 'C:\node-icu\icu4c-54_1-src.zip'
      force: no
  - name: download ICU2C 55 zip
    win_get_url:
      url: 'http://download.icu-project.org/files/icu4c/55.1/icu4c-55_1-src.zip'
      dest: 'C:\node-icu\icu4c-55_1-src.zip'
      force: no
  - name: download ICU2C 56 zip
    win_get_url:
      url: 'http://download.icu-project.org/files/icu4c/56.1/icu4c-56_1-src.zip'
      dest: 'C:\node-icu\icu4c-56_1-src.zip'
      force: no

# Necessary for compressing the Node package
- name: install 7Zip
  win_chocolatey: name=7zip

# Utilities
- block:
  - name: install Sysinternals Suite
    win_chocolatey: name=sysinternals
  - name: install Google Chrome
    win_chocolatey: name=googlechrome
  - name: install Notepad++
    win_chocolatey: name=notepadplusplus
