argument_specs:
  main:
    short_description: The main task for compiling gn from source.
    options:
      gn_dest_dir:
        description: The location to place the symlink to the gn binary.
        required: yes
        type: "str"
      gn_git_dir:
        description: The location to put the git checkout.
        required: yes
        type: "str"
      gn_user:
        default: "{{ server_user|default(omit) }}"
        description: The user to install gn under.
        type: "str"

