---

#
#
#

init: {
  aix: ['aix71', 'aix72'],
  centos6: 'centos6',
  debian: 'debian7',
  freebsd: 'freebsd',
  ibmi: 'ibmi73',
  macos: 'macos',
  rhel7: 'rhel7',
  systemd: ['centos7', 'debian8', 'debian9', 'debian10', 'fedora', 'ubuntu1604', 'ubuntu1804'],
  svc: 'smartos',
  upstart: ['ubuntu12', 'ubuntu1404'],
  zos_start: 'zos'
  }

init_type: "{{ os|match_key(init, raise_error=False)|default(os|stripversion|match_key(init, raise_error=False)) }}"
