---
- hosts: iojs-aix61

  remote_user: root

  tasks:

    - include_vars: ansible-vars.yaml
      tags: vars

    - name: Shells | Add /bin/bash to valid shells
      script: resources/add_bash.sh  creates=/etc/security/login.cfg.old
      tags: user

    - name: User | Add {{ server_user }} user
      user: name="{{ server_user }}" shell=/bin/bash
      tags: user

    - name: Jenkins | Download Jenkins slave.jar
      get_url: url=https://ci.nodejs.org/jnlpJars/slave.jar dest=/home/{{ server_user }}/slave.jar validate_certs=no
      tags: jenkins

    - name: Jenkins | Copy S20jenkins
      copy: src=./resources/S20jenkins dest=/etc/rc.d/rc2.d mode=0755
      tags: jenkins

    - name: Jenkins | Copy certs required to access jenkins/git
      copy: src=./resources/ca-bundle.crt dest=/home/{{ server_user }}/ca-bundle.crt
      tags: jenkins

    - name: Jenkins | Copy server user to jenkins.service
      replace: dest=/etc/rc.d/rc2.d/S20jenkins regexp="\{\{user\}\}" replace="{{ server_user }}"
      tags: jenkins

    - name: Jenkins | Copy secrets to jenkins.service
      replace: dest=/etc/rc.d/rc2.d/S20jenkins regexp="\{\{secret\}\}" replace="{{ server_secret }}"
      tags: jenkins

    - name: Jenkins | Copy server ids to jenkins.service
      replace: dest=/etc/rc.d/rc2.d/S20jenkins regexp="\{\{id\}\}" replace="{{ inventory_hostname }}"
      tags: jenkins
