---

#
# installs java
#

- name: install add-apt-repostory
  when: os in ("ubuntu1204", "ubuntu1404") and arch != "ppc64"
  package: name=software-properties-common state=present

- name: add webupd8 oracle java repository
  when: os in ("ubuntu1204", "ubuntu1404")  and arch != "ppc64"
  apt_repository: repo='ppa:webupd8team/java'

- name: add webupd8team oracle java repository
  when: os == "debian8"
  lineinfile:
    dest: /etc/apt/sources.list
    state: present
    line: deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main

- name: add webupd8team oracle java repository key
  when: os == "debian8"
  shell: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886

- name: accept webupd8 oracle java 8 license
  when: os in ("ubuntu1204", "ubuntu1404") and arch != "ppc64" or os == "debian8"
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: update packages
  when: arch != "ppc64"
  include_role:
    name: package-upgrade

- name: download java
  when: os in "ubuntu1404" and arch == "ppc64"
  get_url:
    url: https://github.com/AdoptOpenJDK/openjdk8-releases/releases/download/jdk8u144-b01/OpenJDK8_ppc64le_Linux_jdk8u144-b01.tar.gz
    dest: /tmp/

- name: unarchive java
  when: os in "ubuntu1404" and arch == "ppc64"
  unarchive:
    src: /tmp/OpenJDK8_ppc64le_Linux_jdk8u144-b01.tar.gz
    remote_src: yes
    dest: /home/iojs
  tags: java

# if this fails you want to check in vars/main.yml and add package name
# as appropriate -- try to use generic os family if available.
- name: install java
  when: not os|startswith("zos") and arch != "ppc64" and not inventory_hostname|regex_search('-arm(v6l|v7l|64)_pi')
  package: name="{{ java_package_name }}" state=present

- name: install webupd8 oracle java 8 extras
  when: os in ("ubuntu1204", "ubuntu1404") and arch != "ppc64"
  package: name="{{item}}" state=present
  with_items:
    - ca-certificates
    - oracle-java8-set-default

- name: pi | uninstall stock java
  when: "inventory_hostname|regex_search('-arm(v6l|v7l|64)_pi')"
  package: name="openjdk-8-jre-headless" state=absent

- name: pi | install java
  when: "inventory_hostname|regex_search('-arm(v6l|v7l|64)_pi')"
  package: name="oracle-java8-jdk" state=present
