---

# For Raspberry Pis of any type, assumed to be running Debian 9

- name: pi | make .ccache
  file:
    path: "/home/{{ server_user }}/.ccache"
    state: directory
    mode: 0755
    owner: "{{ server_user }}"
  ignore_errors: True
  tags: nfs

- name: pi | mount .ccache via nfs
  mount:
    name: "/home/{{ server_user }}/.ccache"
    src: "{{ raspberry_pi.nfs_root_server }}:{{ raspberry_pi.nfs_root_share_root }}/.ccache"
    fstype: nfs4
    opts: rw,exec,async,noauto
    state: mounted
  tags: nfs

- name: pi | copy rc.local to mount nfs post boot
  template:
    src: "./templates/rpi_rc.local.j2"
    dest: "/etc/rc.local"
    owner: "root"
    group: "root"
    mode: 0755
  tags: nfs

- name: pi | copy start_tunnel.sh script
  template:
    src: "./templates/rpi_start_tunnel.j2"
    dest: "/usr/local/sbin/start_tunnel.sh"
    owner: "{{ server_user }}"
    group: "{{ server_user }}"
    mode: 0755
  when: pi_local is defined
  tags: tunnel

- name: pi | crontab entry
  cron:
    name: 'start ssh tunnel on reboot'
    special_time: reboot
    job: "/usr/local/sbin/start_tunnel.sh"
  when: pi_local is defined
  tags: tunnel

- name: pi | configure containers
  set_fact:
    docker_containers: "{{ raspberry_pi.containers[arch] }}"

- import_tasks: "{{ role_path }}/tasks/partials/docker-host.yml"

- name: pi | docker | add pi user to docker group
  user:
    name: "pi"
    groups: "docker"
    append: yes
