---

#
# Install Visual Studio 2019
#


- name: install Visual Studio Community 2019
  win_chocolatey: name=visualstudio2019community

- name: install Visual Studio Community 2019 Native Desktop Workload
  win_chocolatey:
      name: visualstudio2019-workload-nativedesktop
      params: '--add Microsoft.VisualStudio.Component.VC.Tools.ARM64 --add Microsoft.VisualStudio.Component.VC.ATL.ARM64'

- name: install WiX Toolset
  import_tasks: 'wixtoolset.yml'

# Note: https://chocolatey.org/docs/helpers-install-chocolatey-vsix-package exists, but
# can't be used with VS2019 yet: https://github.com/chocolatey/choco/issues/1201

- name: download WiX Toolset Visual Studio Extension
  win_get_url:
    url: 'https://github.com/wixtoolset/VisualStudioExtension/releases/download/v1.0.0.4/Votive2019.vsix'
    dest: 'C:\TEMP\Votive2019.vsix'

- name: install WiX Toolset Visual Studio Extension
  win_shell: '& "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VSIXInstaller.exe" /quiet C:\TEMP\Votive2019.vsix'
