---

#
# Install Visual Studio 2013
#


- name: download Visual Studio Community 2013
  win_get_url:
    url: 'https://go.microsoft.com/fwlink/?LinkId=532495'
    dest: 'C:\TEMP\vs2013_community.exe'

- name: install Visual Studio Community 2013
  win_command: 'C:\TEMP\vs2013_community.exe /Silent /NoRestart
                /Log C:\TEMP\vs2013_install_log.txt'

- name: install WiX Toolset
  import_tasks: 'wixtoolset.yml'
