---

#
# Install WiX Toolset
#

# https://github.com/wixtoolset/issues/issues/5661
- name: install Dot Net 3.5
  win_chocolatey: name=dotnet3.5

- name: install WiX Toolset
  win_chocolatey: name=wixtoolset
