---

#
# set up a jenkins worker -- muy bueno!
#

- hosts:
  - test
  - release
  - "!test-joyent-freebsd10-x64-2"
  - "!test-rackspace-freebsd10-x64-1"

  roles:
    - bootstrap
    - package-upgrade
    - baselayout
    - jenkins-worker

  pre_tasks:
    - name: check if secret is properly set
      fail:
      failed_when: not secret
    - name: check if additional_drive is properly set
      fail:
      failed_when: not additional_drive
      when: "'rhel72-s390x' in inventory_hostname"

  environment: '{{remote_env}}'


#
# Set up Jenkins Workspace servers
#

- hosts:
    - test-packetnet-ubuntu1604-x64-1
    - test-packetnet-ubuntu1604-x64-2
    - test-softlayer-ubuntu1604-x64-1

  roles:
    - jenkins-workspace
