---

#
# set up a jenkins worker -- muy bueno!
#

- hosts:
  - test
  - release
  # Benchmarking machine
  - infra-softlayer-ubuntu1404-x64-2
  - "!*-win*"

  roles:
    - bootstrap
    - package-upgrade
    - baselayout
    - { role: 'benchmarking',
        when: is_benchmark is defined and is_benchmark|bool == True }
    - jenkins-worker

  pre_tasks:
    - name: check if secret is properly set
      fail:
      failed_when: not secret
    - name: check if additional_drive is properly set
      fail:
      failed_when: not additional_drive
      when: "'rhel72-s390x' in inventory_hostname"

  environment: '{{remote_env}}'

#
# Set up Jenkins Workspace servers
#

- hosts:
    - test-packetnet-ubuntu1604-x64-1
    - test-packetnet-ubuntu1604-x64-2
    - test-softlayer-ubuntu1604-x64-1

  roles:
    - jenkins-workspace

#
# Set up ARM cross compiler servers
#

- hosts:
    - test-azure_msft-ubuntu1404-x64-1
    - test-joyent-ubuntu1604_arm_cross-x64-1
    - release-joyent-ubuntu1604_arm_cross-x64-1

  roles:
    - cross-compiler

#
# Install Linux perf on Ubuntu 16.04 servers
#

- hosts:
    - test-*-ubuntu1604-x*
  roles:
    - linux-perf

#
# Set up linter servers
#

- hosts:
   - test-joyent-freebsd10-x64-2
   - test-rackspace-freebsd10-x64-1

  tasks:
    - name: install lint-related packages
      package:
        name: "{{ package }}"
        state: present
      loop_control:
        loop_var: package
      with_items: [ "node", "npm" ]

    - name: install core-validate-commit
      npm:
        name: "core-validate-commit"
        global: yes
        state: present
        production: yes

    - name: periodically update core-validate-commit
      cron:
        special_time: daily
      # ksh does different stdout/err routing
        job: "npm update -g core-validate-commit > & /dev/null"
