---

#
# upgrade `agent.jar` at jenkins workers
#

-  hosts:
    - test
    - release

   tasks:
    - name: download agent.jar
      get_url:
        url: "{{ jenkins_agent_jar }}"
        dest: '{{ home }}/{{ server_user }}/agent.jar'
        mode: 0644
        force: yes

    - name: Kill Jenkins process - AIX
      shell: ps awwx | grep jenkins | grep -v grep | awk '{ print $1 }' | xargs kill
      when: os|startswith("aix")

    - name: Restart Jenkins agent - AIX
      shell: /etc/rc.d/rc2.d/S20jenkins start
      become: yes
      become_user: root
      when: os|startswith("aix")

    - name: Stop Jenkins process - macos
      when: os|startswith("macos")
      command: launchctl unload /Library/LaunchDaemons/org.nodejs.osx.jenkins.plist

    - name: Reload Jenkins process - macos
      when: os|startswith("macos")
      command: launchctl load /Library/LaunchDaemons/org.nodejs.osx.jenkins.plist

    - name: Restart Jenkins service - generic
      when:
        - not os|startswith("aix")
        - not os|startswith("ibmi")
        - not os|startswith("macos")
        - not os|startswith("zos")
      service: name=jenkins state=restarted
