---
- hosts: node-windows

  tasks:

    - name: Download and Install Windows Updates
      win_updates:
        register: update_result

    - name: Reboot machine if necessary
      win_reboot:
        when: update_result.reboot_required

    - name: Create C:\TEMP directory
      win_file: path='C:\TEMP' state=directory

    - name: VCBT2015 | Download .NET Framework Setup
      win_get_url:
        url: 'http://go.microsoft.com/fwlink/?LinkId=671743'
        dest: 'C:\TEMP\netfw.exe'
      tags: [download, visualstudio]

    - name: VCBT2015 | Install .NET Framework
      raw: 'C:\TEMP\netfw.exe /q /norestart
            /log C:\TEMP\netfw_install_log.txt'
      tags: [install, visualstudio]

    - name: VCBT2015 | Download Visual C++ Build Tools 2015 Setup
      win_get_url:
        url: 'https://go.microsoft.com/fwlink/?LinkId=691126&__hstc=268264337.ac84b29e86c2d7ca8d7b5d72067568e7.1497344355585.1497344355585.1497859835361.2&__hssc=268264337.1.1497859835361&__hsfp=589409609&fixForIE=.exe'
        dest: 'C:\TEMP\vcbt2015.exe'
      tags: [download, visualstudio]

    - name: VCBT2015 | Install Visual C++ Build Tools 2015
      raw: 'C:\TEMP\vcbt2015.exe /Silent /NoRestart
            /Full
            /Log C:\TEMP\vsbt2015_install_log.txt'
      tags: [install, visualstudio]

    - name: Reboot machine after Visual C++ Build Tools installation
      win_reboot:

    - include: ./common-ansible-playbook.yaml
      tags: common
