---
- hosts: node-windows

  tasks:

    - name: Download and Install Windows Updates
      win_updates:
      register: update_result

    - name: Reboot machine if necessary
      win_reboot:
      when: update_result.reboot_required

    - name: Create C:\TEMP directory
      win_file: path='C:\TEMP' state=directory

    - name: VS2015 | Download Visual Studio Community 2015 Setup
      win_get_url:
        url: 'https://go.microsoft.com/fwlink/?LinkId=532606'
        dest: 'C:\TEMP\vs_community.exe'
      tags: [download, visualstudio]

    - name: VS2015 | Install Visual Studio Community 2015
      raw: 'C:\TEMP\vs_community.exe /Silent /NoRestart
            /InstallSelectableItems NativeLanguageSupport_Group
            /Log C:\TEMP\vs2015_install_log.txt'
      tags: [install, visualstudio]

    - name: Reboot machine after Visual Studio installation
      win_reboot:

    - import_tasks: ./common-ansible-playbook.yaml
      tags: common
