---
- hosts: node-windows

  tasks:

    - name: Download and Install Windows Updates
      win_updates:
      register: update_result

    - name: Reboot machine if necessary
      win_reboot:
      when: update_result.reboot_required

    - name: Create C:\TEMP directory
      win_file: path='C:\TEMP' state=directory

    - name: VS2013 | Download Visual Studio Community 2013 Setup
      win_get_url:
        url: 'https://go.microsoft.com/fwlink/?LinkId=532495'
        dest: 'C:\TEMP\vs2013_community.exe'
      tags: [download, visualstudio]

    - name: VS2013 | Install Visual Studio Community 2013
      raw: 'C:\TEMP\vs2013_community.exe /Silent /NoRestart
            /Log C:\TEMP\vs2013_install_log.txt'
      tags: [install, visualstudio]

    - name: Reboot machine after Visual Studio installation
      win_reboot:

    - import_tasks: ./common-ansible-playbook.yaml
      tags: common
