---
- hosts: iojs-build-fedora23
  remote_user: root
  gather_facts: False

  tasks:
    - name: Check for python
      raw: which python
      register: python_exists
      failed_when: python_exists.rc > 1

    - name: Bootstrap python
      raw: dnf install -y python2 python2-dnf libselinux-python
      tags: bootstrap
      when: python_exists.rc == 1

- hosts: iojs-build-fedora23
  remote_user: root

  tasks:
    - include_vars: ansible-vars.yaml
      tags: vars

    - name: disable selinux
      selinux: state=disabled
      tags: general

    - name: General | Update all packages
      dnf: name=* state=latest
      tags: general

    - name: General | Install required packages
      dnf: name="{{ packages }}" state=latest
      tags: general

    - name: General | Enable time server
      service: name=systemd-timesyncd state=started enabled=yes
      tags: ntp

    - name: User | Add {{ server_user }} user
      user: name="{{ server_user }}" shell=/bin/bash
      tags: user

    - name: Jenkins | Download Jenkins slave.jar
      get_url: url=https://ci.nodejs.org/jnlpJars/slave.jar dest=/home/{{ server_user }}/slave.jar
      tags: jenkins

    - name: Init | Generate and copy init script
      template: src=./resources/jenkins.service.j2 dest=/lib/systemd/system/jenkins.service
      tags: init

    - name: Init | Start Jenkins
      service: name=jenkins state=started enabled=yes
      tags: init
