---

- name: Bootstrap | Install baseline packages
  package:
    name: "{{ package }}"
    state: present
  loop_control:
    loop_var: package
  with_items: "{{ base_packages }}"

- name: Bootstrap | Ensure keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Bootstrap | Download nodesource signing key
  ansible.builtin.get_url:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    dest: /tmp/nodesource-repo.gpg.key
    mode: '0644'

- name: Bootstrap | De-armoring GPG key
  ansible.builtin.shell:
    cmd: gpg --dearmor < /tmp/nodesource-repo.gpg.key > /etc/apt/keyrings/nodesource.gpg
    creates: /etc/apt/keyrings/nodesource.gpg

- name: Bootstrap | Add nodesource repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_16.x nodistro main"
    state: present

- name: letsencrypt | Add certbot snap
  community.general.snap:
    name: certbot

    classic: true
- name: Bootstrap | APT update and upgrade
  ansible.builtin.apt:
    update_cache: yes
    upgrade: full

- name: Bootstrap | Install and upgrade packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages }}"
  loop_control:
    loop_var: item

- name: Bootstrap | Enable time syncing
  service:
    name: systemd-timesyncd
    state: started
    enabled: yes

- name: Boostrap | Add nodejs user
  user:
    name: "nodejs"
    shell: /bin/bash

- name: Docker | add nodejs user to docker group
  user:
    name: "nodejs"
    groups: "docker"
    append: yes

- name: Init | Create required directories
  file:
    path: "/home/nodejs/{{ item }}"
    state: directory
    mode: 0755
    owner: "nodejs"
  with_items:
    - bin
    - var
    - logs
    - staging
    - download
    - .ccache

- name: letsencrypt | Setup certificate
  shell: certbot --nginx -d 'unofficial-builds.nodejs.org' --email build@iojs.org --agree-tos -n --no-verify-ssl --post-hook "sudo systemctl start nginx" --redirect

- name: Init | Clone unofficial-builds repo
  become: yes
  become_user: "nodejs"
  ansible.builtin.git:
    repo: https://github.com/nodejs/unofficial-builds
    dest: "/home/nodejs/unofficial-builds"
    version: "main"

- name: Deploy Webhook | Install github-webhook
  npm:
    name: github-webhook
    global: yes

- name: Deploy Webhook | Copy config
  template:
    src: "{{ role_path }}/templates/unofficial-builds-deploy-webhook.json.j2"
    dest: "/etc/unofficial-builds-deploy-webhook.json"

- name: Deploy Webhook | Copy deploy script
  copy:
    src: "{{ role_path }}/files/deploy-unofficial-builds.sh"
    dest: "/home/nodejs/bin/deploy-unofficial-builds.sh"
    mode: 0755
    owner: "nodejs"
    group: "nodejs"

- name: Deploy Webhook | Copy init script
  copy:
    src: "{{ role_path }}/files/unofficial-builds-deploy-webhook.service"
    dest: /lib/systemd/system/unofficial-builds-deploy-webhook.service

- name: Deploy Webhook | Start service
  service:
    name: unofficial-builds-deploy-webhook
    state: started
    enabled: yes

- name: Periodic | Copy periodic service unit
  copy:
    src: "{{ role_path }}/files/nodejs-periodic.service"
    dest: /lib/systemd/system/nodejs-periodic.service
    owner: "nodejs"
    group: "nodejs"

- name: Periodic | Copy periodic timer unit
  copy:
    src: "{{ role_path }}/files/nodejs-periodic.timer"
    dest: /lib/systemd/system/nodejs-periodic.timer
    owner: "nodejs"
    group: "nodejs"

- name: Periodic | Register periodic runner
  systemd:
    name: nodejs-periodic.timer
    state: started
    enabled: yes
