---

#
# Install Node build dependencies and other required software
#

- name: install NetWide Assembler
  win_chocolatey: name=nasm

- name: install CMake
  win_chocolatey:
    name: cmake
    install_args: 'ADD_CMAKE_TO_PATH=System'

- name: install Python 3
  win_chocolatey:
    install_args: Include_launcher=1
    name: python3
    pinned: yes
    version: "3.10.8"

- name: install Python 3
  win_chocolatey:
    install_args: Include_launcher=1
    name: python
    pinned: yes
    version: "3.10.8"

- block:
  - name: install Git
    win_chocolatey:
      name: git
      params: '/GitAndUnixToolsOnPath'
  - name: enable long paths in Git
    win_command: 'git config --global core.longpaths true'
  - name: set Git user name
    win_command: 'git config --global user.name "{{inventory_hostname}}"'
  - name: set Git user email
    win_command: 'git config --global user.email "ci@iojs.org"'

# Necessary for junit output in Jenkins jobs
- name: install tap2junit
  win_command: 'pip3 install --upgrade tap2junit'

# Necessary for the libuv test job
- block:
  - name: check if GYP is already cloned
    win_stat: path='C:\gyp'
    register: gyp_stat
  - name: clone GYP repository
    win_command: 'git clone https://chromium.googlesource.com/external/gyp C:\gyp'
    when: not gyp_stat.stat.exists
  - name: update GYP repository
    win_command: 'git pull'
    args: { chdir: 'C:\gyp' }
    when: gyp_stat.stat.exists

# Necessary for compressing the Node package
- name: install 7Zip
  win_chocolatey: name=7zip

# Utilities
- block:
  - name: install Sysinternals Suite
    win_chocolatey: name=sysinternals
  - name: install Google Chrome
    win_chocolatey: name=googlechrome
  - name: install Notepad++
    win_chocolatey: name=notepadplusplus
