---

#
#
#

init: {
  aix: ['aix71', 'aix72', 'aix73'],
  centos6: 'centos6',
  debian: 'debian7',
  freebsd: 'freebsd',
  ibmi: 'ibmi73',
  macos: 'macos',
  systemd: ['centos7', 'debian8', 'debian9', 'debian10', 'fedora', 'rhel7', 'rhel8', 'ubuntu1604', 'ubuntu1804','ubuntu2204'],
  svc: 'smartos',
  upstart: ['ubuntu12', 'ubuntu1404'],
  zos_start: 'zos'
  }

jenkins_init: {
  aix: {
    dest: '/etc/rc.d/rc2.d/S20jenkins',
    src: 'aix.rc2.j2',
    mode: '0555'
    },
  centos6: {
    dest: '/etc/init.d/jenkins',
    src: 'centos6.initd.j2',
    mode: '0755'
    },
  debian: {
    dest: '/etc/init.d/jenkins',
    src: 'sysvinit.initd.j2',
    mode: '0755'
    },
  freebsd: {
    dest: '/usr/local/etc/rc.d/jenkins',
    src: 'freebsd.initd.j2',
    mode: '0755'
    },
  macos: {
    dest: '/Library/LaunchDaemons/org.nodejs.osx.jenkins.plist',
    src: 'org.nodejs.osx.jenkins.plist',
    mode: '0755'
    },
  svc: {
    dest: '/home/{{ server_user }}/jenkins_manifest.xml',
    src: 'jenkins_manifest.xml.j2'
    },
  systemd: {
    dest: '/lib/systemd/system/jenkins.service',
    src: 'systemd.service.j2'
    },
  upstart: {
    dest: '/etc/init/jenkins.conf',
    src: 'upstart.j2'
    },
  zos_start: {
    dest: '{{ home }}/{{ server_user }}/start.sh.utf8',
    src: 'zos_start.j2'
    },
  ibmi: {
    dest: '{{ home }}/{{ server_user }}/jenkins-start.sh',
    src: 'ibmi_start.j2'
    },
  }

# if you fail here, it means it cant map your os or os family to a init system
# the best thing to do would be throwing, but the default case seems to be
# called regardless of success.
init_type: "{{ os|match_key(init, raise_error=False)|default(os|stripversion|match_key(init, raise_error=False)) }}"
jenkins: "{{ jenkins_init[init_type] }}"

needs_monit: [
  'centos6',
  'debian7',
  ]

# some os'es needs different paths to java. add them here.
java_path: {
  'ibmi73': '/QOpenSys/pkgs/lib/jvm/openjdk-11/bin/java',
  'macos10.10': 'java',
  'macos10.11': 'java',
  'macos10.12': 'java',
  'macos10.13': 'java',
  'macos10.14': 'java',
  'macos10.15': 'java',
  'macos11': 'java',
  'macos11.0': 'java',
  'smartos18': '/opt/local/java/openjdk11/bin/java',
  'smartos20': '/opt/local/java/openjdk11/bin/java',
  'zos24': '/usr/lpp/java/J8.0_64/bin/java'
  }

# same for bash. will default to /bin/bash if you don't set it
bash_path: {
  aix: '/usr/bin/ksh',
  freebsd: '/usr/local/bin/bash',
  zos: 'bash'
  }

raspberry_pi: {
  nfs_root_server: '192.168.1.10',
  nfs_root_share_root: '/exports/nodejs/pi',
  containers: {
    armv6l: [
      { name: 'wheezy', template: 'rpi_wheezy.Dockerfile.j2' },
      { name: 'jessie', template: 'rpi_jessie.Dockerfile.j2' }
    ],
    armv7l: [
      { name: 'stretch', template: 'rpi_stretch.Dockerfile.j2' },
      { name: 'buster', template: 'rpi_buster.Dockerfile.j2' }
    ],
    arm64: [
      { name: 'stretch', template: 'rpi_stretch.Dockerfile.j2' },
      { name: 'buster', template: 'rpi_buster.Dockerfile.j2' }
    ]
  }
}

scaleway_armv7: {
  containers: [
      { name: 'jessie', template: 'armv7_jessie.Dockerfile.j2' },
      { name: 'stretch', template: 'armv7_stretch.Dockerfile.j2' }
  ]
}

# primarily for raspberry pi workers, some arm64 workers may need `server_jobs` defined in inventory
# to override these low numbers
jobs_variants: {
  armv6l: '1',
  armv7l: '2',
  arm64: '3',
  smartos: '2'
}

tap2junit_version: 0.1.6
