---

#
# add PPA for gcc updates
#

- name: "repo : add Ubuntu Toolchain PPA"
  apt_repository:
    repo: 'ppa:ubuntu-toolchain-r/test'
    state: present
    update_cache: yes
  register: has_updated_package_repo

# add PPA for Python 3
- name: "repo : add deadsnakes PPA"
  apt_repository:
    repo: 'ppa:deadsnakes/ppa'
    state: present
    update_cache: yes
