---
- hosts: iojs-raspbian
  become: true

  tasks:

    - include_vars: ansible-vars.yaml
      tags: vars

    - name: General | APT Update
      apt:
        update_cache: yes
      tags: general

    - name: General | APT Upgrade
      apt:
        upgrade: dist
      tags: general

    # do this early to speed up login for subsequent actions
    - name: SSH | Remove DNS lookup for login
      lineinfile:
        dest: /etc/ssh/sshd_config
        line: "{{ item }}"
      with_items:
        - "VerifyReverseMapping no"
        - "UseDNS no"
      tags: ssh

    - name: SSH | Restart ssh service
      service: name=ssh state=restarted enabled=yes
      tags: init

    - name: General | Set up 1024M dphys-swapfile
      lineinfile:
        dest: /etc/dphys-swapfile
        state: present
        regexp: '^(\s*)CONF_SWAPSIZE=1024(\s*)$'
        line: 'CONF_SWAPSIZE=1024'
      tags: general

    - name: General | Set up 1024M dphys-swapfile
      shell: dphys-swapfile swapoff && dphys-swapfile setup && dphys-swapfile swapon
      become_user: root
      tags: general

    - name: General | Install required packages
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: latest
      with_items: packages
      tags: general

    - name: gcc | Install gcc 4.8
      when: ansible_distribution_release == 'wheezy'
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: latest
      with_items:
        - gcc-4.8
        - g++-4.8
      tags: gcc

    - name: gcc | Install gcc 4.9
      when: ansible_distribution_release == 'jessie'
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: latest
      with_items:
        - gcc-4.9
        - g++-4.9
      tags: gcc

    - name: gcc | update-alternatives for gcc 4.8
      when: ansible_distribution_release == 'wheezy'
      alternatives:
        name: "{{ item.link }}"
        link: "/usr/bin/{{ item.link }}"
        path: "/usr/bin/{{ item.path }}"
      with_items:
        - { link: 'gcc', path: 'gcc-4.8' }
        - { link: 'cc',  path: 'gcc-4.8' }
        - { link: 'g++', path: 'g++-4.8' }
        - { link: 'c++', path: 'g++-4.8' }
        - { link: 'cpp', path: 'g++-4.8' }
      tags: gcc

    - name: gcc | update-alternatives for gcc 4.9
      when: ansible_distribution_release == 'jessie'
      alternatives:
        name: "{{ item.link }}"
        link: "/usr/bin/{{ item.link }}"
        path: "/usr/bin/{{ item.path }}"
      with_items:
        - { link: 'gcc', path: 'gcc-4.9' }
        - { link: 'cc',  path: 'gcc-4.9' }
        - { link: 'g++', path: 'g++-4.9' }
        - { link: 'c++', path: 'g++-4.9' }
        - { link: 'cpp', path: 'g++-4.9' }
      tags: gcc

    - name: User | Add {{ server_user }} user
      user:
        name: "{{ server_user }}"
        shell: /bin/bash
      tags: user

    - name: NFS | Enable rpcbind service
      service: name=rpcbind state=started enabled=yes
      tags: init

    - name: NFS | Make NFS mounted directories
      file:
        path: "/home/{{ server_user }}/{{ item }}"
        state: directory
        mode: 0755
        owner: "{{ server_user }}"
      with_items:
        - ".ccache"
        - "build"
      ignore_errors: True
      tags: nfs

    - name: NFS | Mount all
      mount:
        name: "/home/{{ server_user }}/{{ item.dst }}"
        src: "{{ nfs_server }}:{{ nfs_share_root }}/{{ item.src }}"
        fstype: nfs
        state: mounted
      with_items:
        - { src: '.ccache', dst: '.ccache' }
        - { src: '{{ server_id }}', dst: 'build' }
      tags: nfs

    - name: Jenkins | Copy start.sh script
      template:
        src: "./resources/start.j2"
        dest: "/home/{{ server_user }}/start.sh"
        owner: "{{ server_user }}"
        group: "{{ server_user }}"
        mode: 0755
      tags: jenkins

    - name: ccache | Install ccache
      include: ../ansible-tasks/ccache.yaml version=3.2.4
      tags: ccache

    - include: ../ansible-tasks/git.yaml version=2.8.1
      tags: git

    - include: ../ansible-tasks/monit.yaml monit_conf_file=../ansible-tasks/resources/monit-jenkins.conf
      tags: monit
