---

- name: docker | register {{ server_user }} GID
  shell: "grep ^{{ server_user }} /etc/group | awk -F: '{print $3}'"
  register: server_user_gid

- name: docker | register {{ server_user }} UID
  shell: "grep ^{{ server_user }} /etc/passwd | awk -F: '{print $4}'"
  register: server_user_uid

- name: docker | fetch latest ccache release version
  local_action: shell curl -sL https://www.samba.org/ftp/ccache/ | awk '{ if (match($0, />ccache-(([0-9]+)\.([0-9]+)\.?([0-9]+)?)\.tar\.gz</, a)) { if (a[2]+0 > maxmaj || (a[2]+0 == maxmaj && a[3]+0 > maxmin) || (a[2]+0 == maxmaj && a[3]+0 == maxmin && a[4]+0 > maxpat)) { maxmaj = a[2]+0; maxmin = a[3]+0; maxpat = a[4]+0; } } } END { printf "%s.%s.%s\n", maxmaj, maxmin, maxpat }'
  register: ccache_latest_result

- name: docker | register ccache version
  set_fact:
    ccache_latest: "{{ ccache_latest_result.stdout }}"

- name: docker | install docker from docker.com
  raw: curl -fsSL get.docker.com | sudo bash -