---

#
# sets up cross compiler machine
#

- name: add ubuntu toolchain ppa
  apt_repository:
    repo: ppa:ubuntu-toolchain-r/test

- name: upgrade installed packages
  apt:
    upgrade: dist
    update_cache: yes

- name: install required packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest

- name: increase file descriptor limits
  lineinfile:
    dest: /etc/security/limits.conf
    line: "{{ item }}"
  with_items:
    - "*         hard    nofile      500000"
    - "*         soft    nofile      500000"
    - "root      hard    nofile      500000"
    - "root      soft    nofile      500000"

- name: clone raspberry tools repository
  git:
    repo: https://github.com/raspberrypi/tools.git
    dest: /opt/raspberrypi/tools

- name: clone newer raspberry tools repository
  git:
    repo: https://github.com/rvagg/rpi-newer-crosstools.git
    dest: /opt/raspberrypi/rpi-newer-crosstools

- name: copy cc-selector.sh script
  copy:
    src: ./files/cc-selector.sh
    dest: /opt/raspberrypi/cc-selector.sh
    mode: 0755
