---
#
# Downloads and installs ccache
# @requires: version=3.2.4
#

- name: "ccache : fetch samba ccache HTML page"
  local_action: shell curl -sL https://www.samba.org/ftp/ccache/
  register: ccache_html_content

- name: "ccache : extract ccache latest version"
  set_fact:
    ccache_latest: "{{ ccache_html_content.stdout | regex_findall('ccache-[0-9]+.[0-9]+(?:.[0-9]+)*.tar.gz') | map('regex_replace', 'ccache-') | list | map('regex_replace', '.tar.gz') | list | latest_version }}"

- name: "ccache : download and extract"
  unarchive:
    dest: /tmp/
    remote_src: yes
    src: "https://www.samba.org/ftp/ccache/ccache-{{ ccache_latest }}.tar.gz"
  register: new_archive

- name: "ccache : prepare for compilation"
  shell: ./configure -q
  args:
    chdir: "/tmp/ccache-{{ ccache_latest }}"

- name: "ccache : compile"
  make: chdir="/tmp/ccache-{{ ccache_latest }}"

- name: "ccache : install"
  copy:
    dest: "/usr/local/bin"
    mode: 0755
    remote_src: yes
    src: "/tmp/ccache-{{ ccache_latest }}/ccache"

- name: "ccache : create symlinks"
  loop_control:
    loop_var: destination
  with_items: [ 'gcc', 'cc', 'g++', 'c++' ]
  file:
    dest: "/usr/local/bin/{{ destination }}"
    src: /usr/local/bin/ccache
    state: link

- name: "ccache : cleanup"
  file: path="/tmp/ccache-{{ ccache_latest }}" state=absent
