jenkins_url: "https://ci-release.nodejs.org"
jenkins_agent_jar: "{{ jenkins_url }}/jnlpJars/agent.jar"
jenkins_icon: "https://ci.nodejs.org/favicon.ico"
server_user: "iojs"
home: "/home"
git_reference_path: "{{ home }}/{{ server_user }}/.ccache/node.shared.reference"
remote_env: {}
