---

#
# installs Linux perf @ /usr/local/bin/perf
#

- stat:
    path=/usr/local/bin/perf
  register: linux_perf
  tags: linux_perf

- name: install perf on linux
  tags: linux_perf
  when: not (linux_perf.stat.exists | bool)
  block:
    - name: Clean path
      file:
        state: absent
        path: /data/tmp/

    - name: Download Linux source code
      git:
        repo: https://github.com/torvalds/linux.git
        depth: 1
        dest: /data/tmp/linux

    - name: Install packages
      package:
        name: "{{ package }}"
        state: present
      loop_control:
        loop_var: package
      with_items: "{{ packages }}"

    - name: build Linux perf
      shell: make -j{{ ansible_processor_cores | default(1) }}
      args:
        chdir: /data/tmp/linux/tools/perf

    - name: install Linux perf
      shell: cp /data/tmp/linux/tools/perf/perf /usr/local/bin/perf

    - name: Clean path
      file:
        state: absent
        path: /data/tmp/
