---

#
# Clear the workspace on jenkins agents
#

- hosts: test
  gather_facts: no
  tasks:

  - name: Check for limit
    fail:
      msg: "No limit set!"
    when: ansible_limit is not defined
    run_once: true

  - name: Gathering facts
    setup:

  - name: remove workspace
    file: 
      path: "{{ home }}/{{ server_user }}/build/workspace"
      state: absent
