---

#
# sets up the host that runs unofficial-builds.nodejs.org
#

- hosts: infra-digitalocean-ubuntu1804-x64-2
  roles:
    - bootstrap
    - package-upgrade
    - baselayout
    - { role: docker, server_user: 'nodejs' }
    - { role: nginx, sites: [ 'unofficial-builds.nodejs.org' ] }
    - unofficial-builds
  pre_tasks:
    # `github_deploy_webhook_secret` should be set in the inventory in secrets.
    - name: check if secrets are properly set
      fail:
      failed_when: not {{ secret }}
      loop_control:
        loop_var: secret
      with_items:
        - github_deploy_webhook_secret
