---

#
# aix: python2.7 is default
#

- name: check if pip exists
  stat:
    path: /usr/bin/pip
  register: pip_exists

- name: download get-pip.py
  get_url:
    url: http://bootstrap.pypa.io/get-pip.py
    dest: /home/iojs/get-pip.py
  when: pip_exists.stat.exists == False

- name: install pip
  raw: /usr/bin/python /home/iojs/get-pip.py
  when: pip_exists.stat.exists == False

- name: create symbolic link
  file:
   src: "/opt/freeware/bin/pip"
   dest: "/usr/bin/pip"
   state: link
  when: pip_exists.stat.exists == False

- name: install tap2junit
  pip: name=tap2junit state=present
