---

#
# centos7: python2.7 is default, python36 (the package name) is available
#

- name: install required packages
  package: name="{{ package }}" state=present
  loop_control:
    loop_var: package
  with_items:
    - python-setuptools, python36

- name: install tap2junit
  raw: easy_install tap2junit
