---

#
# freebsd: python3.8
#

- name: install pip
  package: name=py38-pip state=present

- name: freebsd | update pip3 symlink
  when: os == "freebsd11"
  file:
    dest: "/usr/local/bin/pip3"
    state: link
    src: "/usr/local/bin/pip-3.8"

- name: install tap2junit
  pip: name=tap2junit state=present
