---

#
# freebsd: python3.8
#

- name: install pip
  package:
    name: py39-pip
    state: present

- name: freebsd | update pip3 symlink
  when: os == "freebsd12"
  file:
    dest: "/usr/local/bin/pip3"
    state: link
    src: "/usr/local/bin/pip-3.9"

- name: install tap2junit
  pip:
    executable: pip3
    name: tap2junit=={{ tap2junit_version }}
    state: present
