---

#
# smartos
#

- name: smartos | update pip3 symlink
  when: os == "smartos18"
  file:
    dest: "/opt/local/bin/pip3"
    state: link
    src: "/opt/local/bin/pip3.7"

- name: install tap2junit
  pip:
    executable: /opt/local/bin/pip3
    name: tap2junit=={{ tap2junit_version }}
    state: present
