---

#
# ubuntu series: python 3
#

- name: install pip
  package: name=python3-pip state=present

- name: install tap2junit
  pip: 
    name: tap2junit=={{ tap2junit_version }}
    state: present
    executable: /usr/bin/pip3
