---
- hosts: iojs-build-centos6

  remote_user: root

  tasks:

    - include_vars: ansible-vars.yaml
      tags: vars

    - name: General | yum Update
      yum: name=* state=latest
      tags: general

    - name: General | Add SLC devtoolset repo
      command: curl -sL http://linuxsoft.cern.ch/cern/devtoolset/slc6-devtoolset.repo -o /etc/yum.repos.d/slc6-devtoolset.repo
      tags: general

    - name: General | Add SLC devtoolset repo GPG key
      command: rpm --import http://linuxsoft.cern.ch/cern/slc6X/x86_64/RPM-GPG-KEY-cern
      tags: general

    - name: General | Download SLC SCL repo config
      command: curl http://linuxsoft.cern.ch/cern/scl/slc6-scl.repo -o /etc/yum.repos.d/slc6-scl.repo
      tags: general

    - name: General | Install required packages
      yum: name={{ item }} state=latest
      with_items: "{{ packages }}"
      tags: general

    - name: NTP | Run initial NTP
      command: ntpdate -u pool.ntp.org
      tags: ntp

    - name: NTP | Start NTP
      service: name=ntpd state=started enabled=yes
      tags: ntp

    - name: ccache | Install ccache
      include: ../ansible-tasks/ccache.yaml version=3.3.4
      tags: ccache

    - name: General | Increase file descriptor limits
      lineinfile: dest=/etc/security/limits.conf line="{{ item }}"
      with_items:
        - "*         hard    nofile      500000"
        - "*         soft    nofile      500000"
        - "root      hard    nofile      500000"
        - "root      soft    nofile      500000"
      tags: general

    - name: User | Add {{ server_user }} user
      user: name="{{ server_user }}" shell=/bin/bash
      tags: user

    - name: Jenkins | Download Jenkins' slave.jar
      command: curl -sL https://ci.nodejs.org/jnlpJars/slave.jar -o /home/{{ server_user }}/slave.jar
      tags: jenkins

    - name: Jenkins | Copy init script
      copy: src=./resources/jenkins.initd dest=/etc/init.d/jenkins owner={{ server_user }} group={{ server_user }} mode=0755
      tags: jenkins

    - name: Jenkins | Copy environment files
      template: src=./resources/jenkins.sysconfig.j2 dest=/etc/sysconfig/jenkins owner={{ server_user }} group={{ server_user }} mode=0400
      tags: jenkins

    - name: Jenkins | Enable and start init scripts
      service: name=jenkins enabled=yes state=started
      tags: jenkins
