---

#
# different os'es have different names for java
#

packages: {
  'centos': 'java-1.8.0-openjdk-headless',
  'debian7': 'openjdk-7-jre-headless',
  'debian8': 'oracle-java8-installer',
  'debian9': 'openjdk-8-jre-headless',
  'debian10': 'openjdk-11-jre-headless',
  'fedora': 'java-1.8.0-openjdk-headless',
  'freebsd': 'openjdk8-jre',
  'ibmi': 'openjdk-11-ea',
  'macos10': 'adoptopenjdk8',
  'rhel7': 'java-1.8.0-openjdk',
  'smartos': 'openjdk8',
  'ubuntu': 'openjdk-8-jre-headless',
  'ubuntu1404': 'oracle-java8-installer',
  }

java_package_name: "{{ packages[os]|default(packages[os|stripversion])|default('missing') }}"

# Add os_arch combinations here that should install and use AdoptOpenJDK
# binaries. Override any variables in the dictionary. 
# e.g. on AIX ansible_architecture is 'chrp' on some of our hosts so we
# override arch to be on the safe side.
adoptopenjdk: {
  aix71_ppc64: { arch: ppc64 },
  aix72_ppc64: { arch: ppc64 },
  centos7_ppc64: {},
  rhel7_s390x: {}
}

adoptopenjdk_arch: "{{ adoptopenjdk[os+'_'+arch].arch | default(ansible_architecture) }}"
adoptopenjdk_os: "{{ adoptopenjdk[os+'_'+arch].os | default(ansible_system | lower) }}"
adoptopenjdk_version: "{{ adoptopenjdk[os+'_'+arch].version | default('8') }}"
use_adoptopenjdk: "{{ adoptopenjdk[os+'_'+arch] is defined | bool }}"
