---

#
# set up a jenkins worker -- muy bueno!
#

- hosts:
  - test
  - release

  roles:
    - bootstrap
    - package-upgrade
    - docker

  pre_tasks:
    - name: check if containers property is properly set
      fail:
      failed_when: not containers

  environment: '{{remote_env}}'
