---
- hosts: iojs-build-ubuntu1504
  remote_user: root
  gather_facts: False

  tasks:

    - include_vars: ansible-vars.yaml
      tags: vars

    - name: Boostrap python
      raw: apt-get install -y python
      tags: bootstrap

    - name: General | APT Update and upgrade
      apt: update_cache=yes upgrade=full
      tags: general

    - name: General | Install required packages
      apt: name={{ item }} update_cache=yes state=latest
      with_items: packages
      tags: general

    - name: General | Update certificates
      command: update-ca-certificates -f
      tags: general

    - name: User | Add {{ server_user }} user
      user: name="{{ server_user }}" shell=/bin/bash
      tags: user


    - name: Jenkins | Download Jenkins slave.jar
      get_url: url=https://ci.nodejs.org/jnlpJars/slave.jar dest=/home/{{ server_user }}/slave.jar
      tags: jenkins

    - name: Init | Generate and copy init script
      template: src=./resources/jenkins.service.j2 dest=/lib/systemd/system/jenkins.service
      tags: init

    - name: Init | Start Jenkins
      service: name=jenkins state=started enabled=yes
      tags: init
