---
- hosts: iojs-build-rhel72-linuxonecc

  remote_user: root

  tasks:

    - include_vars: ansible-vars.yaml
      tags: vars

    - name: General | yum Update
      yum: name=* state=latest
      tags: general

    - name: General | Install required packages
      yum: name={{ item }} state=latest
      with_items: packages
      tags: general

    - name: ccache | Install ccache
      include: ../ansible-tasks/ccache.yaml version=3.2.4
      tags: ccache

    - name: NTP | Run initial NTP
      command: ntpdate -u pool.ntp.org
      tags: ntp

    - name: NTP | Start NTP
      service: name=ntpd state=started enabled=yes
      tags: ntp

    - name: User | create file system on larger disk
      filesystem: fstype=ext4 dev={{ additional_drive }}

    - name: User | ensure larger disk is mounted
      mount: name=/data src={{ additional_drive }} fstype=ext4 state=mounted

    - name: User | Add {{ server_user }} user
      user: name="{{ server_user }}" shell=/bin/bash home=/data/iojs
      tags: user

    - name: Firewall | check basic rule to allow communication locally
      command: iptables -C INPUT -s 127.0.0.1/32 -d 127.0.0.1/32 -j ACCEPT
      register: iptables_find_local
      ignore_errors: True
      tags: firewall

    - name: Firewall | add basic rule to allow communication locally
      command: iptables -I INPUT 1 -s 127.0.0.1/32 -d 127.0.0.1/32 -j ACCEPT
      when: iptables_find_local|failed
      tags: firewall

    - name: Firewall | check additional rule to allow communication from 127.0.0.2
      command: iptables -C INPUT -s 127.0.0.2/32 -d 127.0.0.1/32 -j ACCEPT
      register: iptables_find_local2
      ignore_errors: True
      tags: firewall

    - name: Firewall | add additional rule to allow communication from 127.0.0.2
      command: iptables -I INPUT 1 -s 127.0.0.2/32 -d 127.0.0.1/32 -j ACCEPT
      when: iptables_find_local2|failed
      tags: firewall

    - name: Firewall | check basic rule to allow communication on test port
      command: iptables -C INPUT -p udp --dport 12346 -j ACCEPT
      register: iptables_find_testport
      ignore_errors: True
      tags: firewall

    - name: Firewall | add basic rule to allow communication on test port
      command: iptables -I INPUT 1 -p udp --dport 12346 -j ACCEPT
      when: iptables_find_testport|failed
      tags: firewall

    - name: Firewall | check rule to prevent external communication to test port
      command: iptables -t nat -C PREROUTING -p udp --dport 12346 -j DNAT --to 127.0.0.1:12345
      register: iptables_find_nattestport
      ignore_errors: True
      tags: firewall

    - name: Firewall | add rule to prevent external communication to test port
      command: iptables -t nat -A PREROUTING -p udp --dport 12346 -j DNAT --to 127.0.0.1:12345
      when: iptables_find_nattestport|failed
      tags: firewall

    - name: Firewall | add basic rule to allow communication locally
      shell: iptables-save > /etc/sysconfig/iptables
      tags: firewall

    - name: Jenkins | Download Jenkins slave.jar
      get_url: url=https://ci.nodejs.org/jnlpJars/slave.jar dest=/data/{{ server_user }}/slave.jar
      tags: jenkins

    - name: Init | Generate and copy init script
      template: src=./resources/jenkins.service.j2 dest=/usr/lib/systemd/system/jenkins.service mode=0644
      tags: init

    - name: Jenkins | Start Jenkins service
      service: name=jenkins state=started enabled=yes
      tags: jenkins
