---

#
# centos6 - almost getting there
#

- name: "repo : add devtoolset-2"
  get_url:
    url: http://people.centos.org/tru/devtools-2/devtools-2.repo
    dest: /etc/yum.repos.d/devtoolset-2.repo
    mode: 0440

- name: "repo : add epel"
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present

- name: "repo : add epel key"
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
    state: present
