---

- name: centos6 | install epel
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm"
    state: present

- name: centos6 | install ius
  yum:
    name: "https://centos6.iuscommunity.org/ius-release.rpm"
    state: present

- name: centos6 | install devtoolset-2 repo
  get_url:
    url: http://people.centos.org/tru/devtools-2/devtools-2.repo
    dest: /etc/yum.repos.d/devtools-2.repo
    mode: 0644
