---

- name: centos6 | install epel
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present

- name: centos6 | install ius
  yum:
    name: "https://repo.ius.io/ius-release-el{{ ansible_distribution_major_version }}.rpm "
    state: present

- name: centos6 | install scl for devtoolset-6
  yum:
    name: centos-release-scl
    state: present

- name: centos6 | install devtoolset-2 repo
  get_url:
    url: http://people.centos.org/tru/devtools-2/devtools-2.repo
    dest: /etc/yum.repos.d/devtools-2.repo
    mode: 0644

- name: centos6 | install devtoolset-6 for i686
  when: "arch == 'x86'"
  get_url:
    url: "https://copr.fedorainfracloud.org/coprs/mlampe/devtoolset-6.1/repo/epel-6/mlampe-devtoolset-6.1-epel-6.repo"
    dest: "/etc/yum.repos.d/mlampe-devtoolset-6.1-epel-6.repo"
    mode: 0644
