---

- name: "repo : add ubuntu toolchain ppa"
  apt_repository:
    repo: 'ppa:ubuntu-toolchain-r/test'
    state: present
    update_cache: yes
  register: has_updated_package_repo

- name: "repo : add git-core ppa"
  apt_repository:
    repo: ppa:git-core/ppa
    state: present
    update_cache: yes
  register: has_updated_package_repo
