---

#
# add PPA for gcc 4.9
#

- name: "repo : add Ubuntu Toolchain PPA"
  apt_repository:
    repo: 'ppa:ubuntu-toolchain-r/test'
    state: present
    update_cache: yes
  register: has_updated_package_repo
