---

# Set up tooling required to perform static analysis builds.
# See MANUAL_STEPS.md for further steps if the Build tool is updated.

# Required to submit builds to Coverity.
- name: Install jq
  ansible.builtin.package:
    name: jq
    state: latest
    update_cache: yes

# Coverity build tool.
- name: Get md5sum for Coverity build tool
  ansible.builtin.uri:
    body:
      md5: 1
      token: "{{ secrets.coverity_token }}"
      project: Node.js
    body_format: form-urlencoded
    method: POST
    url: https://scan.coverity.com/download/linux64
    return_content: true
  register: coverity_build_tool_meta

- name: Download Coverity build tool
  ansible.builtin.uri:
    body:
      token: "{{ secrets.coverity_token }}"
      project: Node.js
    body_format: form-urlencoded
    dest: /tmp/
    method: POST
    url: https://scan.coverity.com/download/linux64
  register: coverity_build_tool

- name: Validate checksum of downloaded Coverity build tool
  ansible.builtin.stat:
    checksum_algorithm: md5
    path: "{{ coverity_build_tool.path }}"
  failed_when: coverity_build_tool_file.stat.checksum != coverity_build_tool_meta.content
  register: coverity_build_tool_file

- name: Unpack Coverity build tool
  ansible.builtin.unarchive:
    creates: "/var/{{ coverity_build_tool.path|regex_search('/tmp/(.+)\\.tar\\.gz', '\\1')|first }}"
    dest: /var/
    remote_src: true
    src: "{{ coverity_build_tool.path }}"
