---
- hosts: iojs-build-smartos

  remote_user: root

  vars:
    - ansible_python_interpreter: "/usr/bin/env python"

  tasks:

    - include_vars: ansible-vars.yaml
      tags: vars

    - name: General | pkgin Update
      command: pkgin up
      tags: general

    - name: General | Install required packages
      command: pkgin -y in {{ item }}
      with_items: packages
      tags: general

    - name: User | Add {{ server_user }} group
      command: groupadd {{ server_user }}
      tags: user

    - name: User | Add {{ server_user }} user
      user: name="{{ server_user }}" shell=/bin/bash append=yes groups=staff,{{ server_user }}
      tags: user

    - name: User | Unlock {{ server_user }} user
      command: passwd -N {{ server_user }}
      tags: user

    - name: CCache | Create directory that hold symlinks to ccache
      file: path=/opt/local/libexec/ccache state=directory mode=0755
      tags: ccache

    - name: CCache | Symlink compiler binaries to ccache
      file: src={{ item.src }} dest={{ item.dest }} state=link
      with_items:
        - { src: '/opt/local/bin/ccache', dest: '/opt/local/libexec/ccache/gcc' }
        - { src: '/opt/local/bin/ccache', dest: '/opt/local/libexec/ccache/g++' }
      tags: ccache

    - name: Jenkins | Download Jenkins slave.jar
      get_url: url=https://ci.nodejs.org/jnlpJars/slave.jar dest=/home/{{ server_user }}/slave.jar
      tags: jenkins

    - name: Jenkins | Copy SMF manifest
      template: src=./resources/jenkins_manifest.xml.j2 dest=/home/{{ server_user }}/jenkins_manifest.xml
      tags: jenkins

    - name: Jenkins | Import jenkins SMF manifest
      command: svccfg -v import /home/{{ server_user }}/jenkins_manifest.xml
      tags: jenkins

    - name: Jenkins | Start service
      command: svcadm enable svc:/application/jenkins:default
      tags: jenkins
