---

#
# create a jenkins host
#

- hosts:
  - infra-digitalocean-ubuntu2204-x64-1 # ci.nodejs.org
  - infra-ibm-ubuntu2404-x64-1 # ci-release.nodejs.org

  roles:
  - bootstrap
  - baselayout

  tasks:
#    - name: place init script
