---

#
# Updates all packages for debian-based distributions
#

- name: upgrade installed packages
  apt:
    update_cache: yes
    upgrade: dist

- name: clean unwanted packages
  apt:
    autoremove: yes
