---

#
# variables shared in baselayout
#

binary_dest: '/usr/local/bin/ccache'

ccache_no_binpkg: ['smartos14', 'smartos15', 'smartos16']
ccache_version: 3.3.2

git_no_binpkg: ['debian7']
git_version: 2.10.2

ssh_config: /etc/ssh/sshd_config

sshd_service_map: {
  'ubuntu1404': 'ssh',
  'ubuntu1204': 'ssh',
}

sshd_service_name: "{{ sshd_service_map[os]|default(sshd_service_map[os|stripversion])|default('sshd') }}"

ntp_service: {
  systemd: ['debian8', 'debian9', 'ubuntu1604', 'ubuntu1610', 'ubuntu1710'],
  ntp_package: ['ubuntu1404']
}

common_packages: [
  'automake',
  'bash',
  'libtool',
  'sudo',
]

# you can either add os family or os to this list (see smartos)
# but the playbook chooses os over family - not both
packages: {
  centos: [
    'ccache',
    'git',
    'gcc-c++', # even need this on centos6 so ccache has symlinks
  ],

  debian7: [
    'gcc-4.8',
    'g++-4.8',
  ],

  debian8: [
    'ccache',
    'git',
    'libfontconfig1',
  ],

  debian9: [
    'gcc-6,g++-6,ccache,git,curl,libfontconfig1,apt-transport-https,ca-certificates',
  ],

  fedora: [
    'bzip2',
    'ccache',
    'gcc-c++',
    'git',
    'fontconfig',
  ],

  freebsd: [
    'ccache',
    'git',
    'gmake'
  ],

  rhel72: [
    'gcc-c++',
  ],

  smartos14: [
    'gcc48',
    'gcc48-libs',
    'gccmakedep',
    'git',
    'gmake',
    'xz'
  ],

  smartos15: [
    'gcc49',
    'gcc49-libs',
    'gccmakedep',
    'git',
    'gmake',
    'xz'
  ],

  smartos16: [
    'gcc49',
    'gcc49-libs',
    'gccmakedep',
    'git',
    'gmake',
    'xz'
  ],

  ubuntu: [
    'ccache',
    'g++',
    'gcc',
    'git',
    'libfontconfig1',
  ],

  ubuntu1404: [
    'ntp',
    'g++-4.8',
    'gcc-4.8',
    'g++-4.9',
    'gcc-4.9',
  ]
}
