name: Lint Python
on:
  push:
    branches-ignore:
      - "dependabot/*"
    paths:
      - '**/*.py'
      - '.flake8'
      - .github/workflows/lint-python.yml
  pull_request:
    paths:
      - '**/*.py'
      - '.flake8'
      - .github/workflows/lint-python.yml
jobs:
  Python:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Lint with flake8
      run: |
        flake8 --version
        flake8 .
