name: Lint
on:
  push:
    branches-ignore:
      - "dependabot/*"
  pull_request:
permissions:
  contents: read

jobs:
  Python:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
    - name: Set up Python 3.7
      uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install -r requirements.txt  # TODO: Add tap2junit
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --version
        flake8 .
