name: Shellcheck
on:
  push:
    paths:
      - '**/*.sh'
      - '.github/workflows/shellcheck.yml'
      - '.shellcheckrc'
  pull_request:
    paths:
      - '**/*.sh'
      - '.github/workflows/shellcheck.yml'
      - '.shellcheckrc'

permissions:
  contents: read

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
    - name: ShellCheck
      uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # 2.0.0
      with:
        check_together: 'yes'
